require("prototypes.item-groups")
require("prototypes.item")
require("prototypes.fluid")
require("prototypes.recipe")
require("prototypes.technology")
require("prototypes.entity.entities")
require("prototypes.entity.explosions")
require("prototypes.entity.remnants")
